=== NalaGinrut/mimosa/config/config.dtd
<!ELEMENT config (arch,memory,mmu,boot)>

<!ELEMENT arch (family,bitwidth)>
<!ELEMENT family (#PCDATA)>
<!ELEMENT bitwidth (#PCDATA)>

<!ELEMENT memory (kern_base,kern_stack)>
<!ELEMENT kern_base (#PCDATA)>
<!ELEMENT kern_stack (#PCDATA)>

<!ELEMENT mmu (page)>
<!ELEMENT page (enabled,pt_level,pg_size)>
<!ELEMENT enabled (#PCDATA)>
<!ELEMENT pt_level (#PCDATA)>
<!ELEMENT pg_size (#PCDATA)>

<!ELEMENT boot (grub)>
<!ELEMENT grub (#PCDATA)>

=== NalaGinrut/mimosa/config/platforms-xml/x86.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "mimosa-config" "../config.dtd">
<config>
  
  <arch>
    <family>i386</family>
    <bitwidth>32</bitwidth>
  </arch>

  <memory>
    <kern_base>0xC010000C</kern_base>
    <kern_stack>1</kern_stack>
  </memory>

  <mmu>  
    <page>
      <enabled>true</enabled>
      <pt_level>3</pt_level>
      <pg_size>0x1000</pg_size>  
    </page>
  </mmu>

  <boot>
    <grub>true</grub>
  </boot>
  
</config>
